/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminApiRouteImport } from './routes/admin/api'
import { Route as AdminBotRouteImport } from './routes/admin/bot'
import { Route as AdminDatabaseRouteImport } from './routes/admin/database'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminMaintenanceRouteImport } from './routes/admin/maintenance'
import { Route as AdminModulesRouteImport } from './routes/admin/modules'
import { Route as AdminServersRouteImport } from './routes/admin/servers'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCommandsRouteImport } from './routes/dashboard/commands'
import { Route as DashboardServersRouteImport } from './routes/dashboard/servers'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AdminServersGuildIdRouteImport } from './routes/admin/servers.$guildId'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as DashboardServersIndexRouteImport } from './routes/dashboard/servers.index'
import { Route as DashboardServersGuildIdRouteImport } from './routes/dashboard/servers.$guildId'
import { Route as ApiPublicAuthLogoutRouteImport } from './routes/api/public/auth/logout'
import { Route as DashboardServersGuildIdIndexRouteImport } from './routes/dashboard/servers.$guildId.index'
import { Route as DashboardServersGuildIdAutomodRouteImport } from './routes/dashboard/servers.$guildId.automod'
import { Route as DashboardServersGuildIdAutoreactRouteImport } from './routes/dashboard/servers.$guildId.autoreact'
import { Route as DashboardServersGuildIdAutoroleRouteImport } from './routes/dashboard/servers.$guildId.autorole'
import { Route as DashboardServersGuildIdCustomrolesRouteImport } from './routes/dashboard/servers.$guildId.customroles'
import { Route as DashboardServersGuildIdInvcroleRouteImport } from './routes/dashboard/servers.$guildId.invcrole'
import { Route as DashboardServersGuildIdInvitesRouteImport } from './routes/dashboard/servers.$guildId.invites'
import { Route as DashboardServersGuildIdJ2cRouteImport } from './routes/dashboard/servers.$guildId.j2c'
import { Route as DashboardServersGuildIdJoindmRouteImport } from './routes/dashboard/servers.$guildId.joindm'
import { Route as DashboardServersGuildIdLevelingRouteImport } from './routes/dashboard/servers.$guildId.leveling'
import { Route as DashboardServersGuildIdLoggingRouteImport } from './routes/dashboard/servers.$guildId.logging'
import { Route as DashboardServersGuildIdProtectionRouteImport } from './routes/dashboard/servers.$guildId.protection'
import { Route as DashboardServersGuildIdReactionrolesRouteImport } from './routes/dashboard/servers.$guildId.reactionroles'
import { Route as DashboardServersGuildIdTicketsRouteImport } from './routes/dashboard/servers.$guildId.tickets'
import { Route as DashboardServersGuildIdTrackingRouteImport } from './routes/dashboard/servers.$guildId.tracking'
import { Route as DashboardServersGuildIdVanityrolesRouteImport } from './routes/dashboard/servers.$guildId.vanityroles'
import { Route as DashboardServersGuildIdVerificationRouteImport } from './routes/dashboard/servers.$guildId.verification'
import { Route as DashboardServersGuildIdWelcomeRouteImport } from './routes/dashboard/servers.$guildId.welcome'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'
import { Route as ApiPublicAuthDiscordLoginRouteImport } from './routes/api/public/auth/discord/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotRoute = AdminBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatabaseRoute = AdminDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServersRoute = AdminServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommandsRoute = DashboardCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServersRoute = DashboardServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminServersGuildIdRoute = AdminServersGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => AdminServersRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServersIndexRoute = DashboardServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardServersRoute,
} as any)
const DashboardServersGuildIdRoute = DashboardServersGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => DashboardServersRoute,
} as any)
const ApiPublicAuthLogoutRoute = ApiPublicAuthLogoutRouteImport.update({
  id: '/api/public/auth/logout',
  path: '/api/public/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServersGuildIdIndexRoute =
  DashboardServersGuildIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdAutomodRoute =
  DashboardServersGuildIdAutomodRouteImport.update({
    id: '/automod',
    path: '/automod',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdAutoreactRoute =
  DashboardServersGuildIdAutoreactRouteImport.update({
    id: '/autoreact',
    path: '/autoreact',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdAutoroleRoute =
  DashboardServersGuildIdAutoroleRouteImport.update({
    id: '/autorole',
    path: '/autorole',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdCustomrolesRoute =
  DashboardServersGuildIdCustomrolesRouteImport.update({
    id: '/customroles',
    path: '/customroles',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdInvcroleRoute =
  DashboardServersGuildIdInvcroleRouteImport.update({
    id: '/invcrole',
    path: '/invcrole',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdInvitesRoute =
  DashboardServersGuildIdInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdJ2cRoute =
  DashboardServersGuildIdJ2cRouteImport.update({
    id: '/j2c',
    path: '/j2c',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdJoindmRoute =
  DashboardServersGuildIdJoindmRouteImport.update({
    id: '/joindm',
    path: '/joindm',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdLevelingRoute =
  DashboardServersGuildIdLevelingRouteImport.update({
    id: '/leveling',
    path: '/leveling',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdLoggingRoute =
  DashboardServersGuildIdLoggingRouteImport.update({
    id: '/logging',
    path: '/logging',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdProtectionRoute =
  DashboardServersGuildIdProtectionRouteImport.update({
    id: '/protection',
    path: '/protection',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdReactionrolesRoute =
  DashboardServersGuildIdReactionrolesRouteImport.update({
    id: '/reactionroles',
    path: '/reactionroles',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdTicketsRoute =
  DashboardServersGuildIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdTrackingRoute =
  DashboardServersGuildIdTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdVanityrolesRoute =
  DashboardServersGuildIdVanityrolesRouteImport.update({
    id: '/vanityroles',
    path: '/vanityroles',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdVerificationRoute =
  DashboardServersGuildIdVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const DashboardServersGuildIdWelcomeRoute =
  DashboardServersGuildIdWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => DashboardServersGuildIdRoute,
  } as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordLoginRoute =
  ApiPublicAuthDiscordLoginRouteImport.update({
    id: '/api/public/auth/discord/login',
    path: '/api/public/auth/discord/login',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/commands': typeof CommandsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/invite': typeof InviteRoute
  '/status': typeof StatusRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/servers': typeof AdminServersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/commands': typeof DashboardCommandsRoute
  '/dashboard/servers': typeof DashboardServersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/servers/$guildId': typeof AdminServersGuildIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/dashboard/servers/$guildId': typeof DashboardServersGuildIdRouteWithChildren
  '/dashboard/servers/': typeof DashboardServersIndexRoute
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/dashboard/servers/$guildId/automod': typeof DashboardServersGuildIdAutomodRoute
  '/dashboard/servers/$guildId/autoreact': typeof DashboardServersGuildIdAutoreactRoute
  '/dashboard/servers/$guildId/autorole': typeof DashboardServersGuildIdAutoroleRoute
  '/dashboard/servers/$guildId/customroles': typeof DashboardServersGuildIdCustomrolesRoute
  '/dashboard/servers/$guildId/invcrole': typeof DashboardServersGuildIdInvcroleRoute
  '/dashboard/servers/$guildId/invites': typeof DashboardServersGuildIdInvitesRoute
  '/dashboard/servers/$guildId/j2c': typeof DashboardServersGuildIdJ2cRoute
  '/dashboard/servers/$guildId/joindm': typeof DashboardServersGuildIdJoindmRoute
  '/dashboard/servers/$guildId/leveling': typeof DashboardServersGuildIdLevelingRoute
  '/dashboard/servers/$guildId/logging': typeof DashboardServersGuildIdLoggingRoute
  '/dashboard/servers/$guildId/protection': typeof DashboardServersGuildIdProtectionRoute
  '/dashboard/servers/$guildId/reactionroles': typeof DashboardServersGuildIdReactionrolesRoute
  '/dashboard/servers/$guildId/tickets': typeof DashboardServersGuildIdTicketsRoute
  '/dashboard/servers/$guildId/tracking': typeof DashboardServersGuildIdTrackingRoute
  '/dashboard/servers/$guildId/vanityroles': typeof DashboardServersGuildIdVanityrolesRoute
  '/dashboard/servers/$guildId/verification': typeof DashboardServersGuildIdVerificationRoute
  '/dashboard/servers/$guildId/welcome': typeof DashboardServersGuildIdWelcomeRoute
  '/dashboard/servers/$guildId/': typeof DashboardServersGuildIdIndexRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/invite': typeof InviteRoute
  '/status': typeof StatusRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/servers': typeof AdminServersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/commands': typeof DashboardCommandsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/servers/$guildId': typeof AdminServersGuildIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/dashboard/servers': typeof DashboardServersIndexRoute
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/dashboard/servers/$guildId/automod': typeof DashboardServersGuildIdAutomodRoute
  '/dashboard/servers/$guildId/autoreact': typeof DashboardServersGuildIdAutoreactRoute
  '/dashboard/servers/$guildId/autorole': typeof DashboardServersGuildIdAutoroleRoute
  '/dashboard/servers/$guildId/customroles': typeof DashboardServersGuildIdCustomrolesRoute
  '/dashboard/servers/$guildId/invcrole': typeof DashboardServersGuildIdInvcroleRoute
  '/dashboard/servers/$guildId/invites': typeof DashboardServersGuildIdInvitesRoute
  '/dashboard/servers/$guildId/j2c': typeof DashboardServersGuildIdJ2cRoute
  '/dashboard/servers/$guildId/joindm': typeof DashboardServersGuildIdJoindmRoute
  '/dashboard/servers/$guildId/leveling': typeof DashboardServersGuildIdLevelingRoute
  '/dashboard/servers/$guildId/logging': typeof DashboardServersGuildIdLoggingRoute
  '/dashboard/servers/$guildId/protection': typeof DashboardServersGuildIdProtectionRoute
  '/dashboard/servers/$guildId/reactionroles': typeof DashboardServersGuildIdReactionrolesRoute
  '/dashboard/servers/$guildId/tickets': typeof DashboardServersGuildIdTicketsRoute
  '/dashboard/servers/$guildId/tracking': typeof DashboardServersGuildIdTrackingRoute
  '/dashboard/servers/$guildId/vanityroles': typeof DashboardServersGuildIdVanityrolesRoute
  '/dashboard/servers/$guildId/verification': typeof DashboardServersGuildIdVerificationRoute
  '/dashboard/servers/$guildId/welcome': typeof DashboardServersGuildIdWelcomeRoute
  '/dashboard/servers/$guildId': typeof DashboardServersGuildIdIndexRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/commands': typeof CommandsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/invite': typeof InviteRoute
  '/status': typeof StatusRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/servers': typeof AdminServersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/commands': typeof DashboardCommandsRoute
  '/dashboard/servers': typeof DashboardServersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/servers/$guildId': typeof AdminServersGuildIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/dashboard/servers/$guildId': typeof DashboardServersGuildIdRouteWithChildren
  '/dashboard/servers/': typeof DashboardServersIndexRoute
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/dashboard/servers/$guildId/automod': typeof DashboardServersGuildIdAutomodRoute
  '/dashboard/servers/$guildId/autoreact': typeof DashboardServersGuildIdAutoreactRoute
  '/dashboard/servers/$guildId/autorole': typeof DashboardServersGuildIdAutoroleRoute
  '/dashboard/servers/$guildId/customroles': typeof DashboardServersGuildIdCustomrolesRoute
  '/dashboard/servers/$guildId/invcrole': typeof DashboardServersGuildIdInvcroleRoute
  '/dashboard/servers/$guildId/invites': typeof DashboardServersGuildIdInvitesRoute
  '/dashboard/servers/$guildId/j2c': typeof DashboardServersGuildIdJ2cRoute
  '/dashboard/servers/$guildId/joindm': typeof DashboardServersGuildIdJoindmRoute
  '/dashboard/servers/$guildId/leveling': typeof DashboardServersGuildIdLevelingRoute
  '/dashboard/servers/$guildId/logging': typeof DashboardServersGuildIdLoggingRoute
  '/dashboard/servers/$guildId/protection': typeof DashboardServersGuildIdProtectionRoute
  '/dashboard/servers/$guildId/reactionroles': typeof DashboardServersGuildIdReactionrolesRoute
  '/dashboard/servers/$guildId/tickets': typeof DashboardServersGuildIdTicketsRoute
  '/dashboard/servers/$guildId/tracking': typeof DashboardServersGuildIdTrackingRoute
  '/dashboard/servers/$guildId/vanityroles': typeof DashboardServersGuildIdVanityrolesRoute
  '/dashboard/servers/$guildId/verification': typeof DashboardServersGuildIdVerificationRoute
  '/dashboard/servers/$guildId/welcome': typeof DashboardServersGuildIdWelcomeRoute
  '/dashboard/servers/$guildId/': typeof DashboardServersGuildIdIndexRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/commands'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/invite'
    | '/status'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/api'
    | '/admin/bot'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/maintenance'
    | '/admin/modules'
    | '/admin/servers'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/commands'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/servers/$guildId'
    | '/api/public/health'
    | '/dashboard/servers/$guildId'
    | '/dashboard/servers/'
    | '/api/public/auth/logout'
    | '/dashboard/servers/$guildId/automod'
    | '/dashboard/servers/$guildId/autoreact'
    | '/dashboard/servers/$guildId/autorole'
    | '/dashboard/servers/$guildId/customroles'
    | '/dashboard/servers/$guildId/invcrole'
    | '/dashboard/servers/$guildId/invites'
    | '/dashboard/servers/$guildId/j2c'
    | '/dashboard/servers/$guildId/joindm'
    | '/dashboard/servers/$guildId/leveling'
    | '/dashboard/servers/$guildId/logging'
    | '/dashboard/servers/$guildId/protection'
    | '/dashboard/servers/$guildId/reactionroles'
    | '/dashboard/servers/$guildId/tickets'
    | '/dashboard/servers/$guildId/tracking'
    | '/dashboard/servers/$guildId/vanityroles'
    | '/dashboard/servers/$guildId/verification'
    | '/dashboard/servers/$guildId/welcome'
    | '/dashboard/servers/$guildId/'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commands'
    | '/docs'
    | '/features'
    | '/invite'
    | '/status'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/api'
    | '/admin/bot'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/maintenance'
    | '/admin/modules'
    | '/admin/servers'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/commands'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/servers/$guildId'
    | '/api/public/health'
    | '/dashboard/servers'
    | '/api/public/auth/logout'
    | '/dashboard/servers/$guildId/automod'
    | '/dashboard/servers/$guildId/autoreact'
    | '/dashboard/servers/$guildId/autorole'
    | '/dashboard/servers/$guildId/customroles'
    | '/dashboard/servers/$guildId/invcrole'
    | '/dashboard/servers/$guildId/invites'
    | '/dashboard/servers/$guildId/j2c'
    | '/dashboard/servers/$guildId/joindm'
    | '/dashboard/servers/$guildId/leveling'
    | '/dashboard/servers/$guildId/logging'
    | '/dashboard/servers/$guildId/protection'
    | '/dashboard/servers/$guildId/reactionroles'
    | '/dashboard/servers/$guildId/tickets'
    | '/dashboard/servers/$guildId/tracking'
    | '/dashboard/servers/$guildId/vanityroles'
    | '/dashboard/servers/$guildId/verification'
    | '/dashboard/servers/$guildId/welcome'
    | '/dashboard/servers/$guildId'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/commands'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/invite'
    | '/status'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/api'
    | '/admin/bot'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/maintenance'
    | '/admin/modules'
    | '/admin/servers'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/commands'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/servers/$guildId'
    | '/api/public/health'
    | '/dashboard/servers/$guildId'
    | '/dashboard/servers/'
    | '/api/public/auth/logout'
    | '/dashboard/servers/$guildId/automod'
    | '/dashboard/servers/$guildId/autoreact'
    | '/dashboard/servers/$guildId/autorole'
    | '/dashboard/servers/$guildId/customroles'
    | '/dashboard/servers/$guildId/invcrole'
    | '/dashboard/servers/$guildId/invites'
    | '/dashboard/servers/$guildId/j2c'
    | '/dashboard/servers/$guildId/joindm'
    | '/dashboard/servers/$guildId/leveling'
    | '/dashboard/servers/$guildId/logging'
    | '/dashboard/servers/$guildId/protection'
    | '/dashboard/servers/$guildId/reactionroles'
    | '/dashboard/servers/$guildId/tickets'
    | '/dashboard/servers/$guildId/tracking'
    | '/dashboard/servers/$guildId/vanityroles'
    | '/dashboard/servers/$guildId/verification'
    | '/dashboard/servers/$guildId/welcome'
    | '/dashboard/servers/$guildId/'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommandsRoute: typeof CommandsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  InviteRoute: typeof InviteRoute
  StatusRoute: typeof StatusRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicAuthLogoutRoute: typeof ApiPublicAuthLogoutRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordLoginRoute: typeof ApiPublicAuthDiscordLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bot': {
      id: '/admin/bot'
      path: '/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AdminBotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/database': {
      id: '/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminDatabaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servers': {
      id: '/admin/servers'
      path: '/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AdminServersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/commands': {
      id: '/dashboard/commands'
      path: '/commands'
      fullPath: '/dashboard/commands'
      preLoaderRoute: typeof DashboardCommandsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servers': {
      id: '/dashboard/servers'
      path: '/servers'
      fullPath: '/dashboard/servers'
      preLoaderRoute: typeof DashboardServersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/servers/$guildId': {
      id: '/admin/servers/$guildId'
      path: '/$guildId'
      fullPath: '/admin/servers/$guildId'
      preLoaderRoute: typeof AdminServersGuildIdRouteImport
      parentRoute: typeof AdminServersRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servers/': {
      id: '/dashboard/servers/'
      path: '/'
      fullPath: '/dashboard/servers/'
      preLoaderRoute: typeof DashboardServersIndexRouteImport
      parentRoute: typeof DashboardServersRoute
    }
    '/dashboard/servers/$guildId': {
      id: '/dashboard/servers/$guildId'
      path: '/$guildId'
      fullPath: '/dashboard/servers/$guildId'
      preLoaderRoute: typeof DashboardServersGuildIdRouteImport
      parentRoute: typeof DashboardServersRoute
    }
    '/api/public/auth/logout': {
      id: '/api/public/auth/logout'
      path: '/api/public/auth/logout'
      fullPath: '/api/public/auth/logout'
      preLoaderRoute: typeof ApiPublicAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servers/$guildId/': {
      id: '/dashboard/servers/$guildId/'
      path: '/'
      fullPath: '/dashboard/servers/$guildId/'
      preLoaderRoute: typeof DashboardServersGuildIdIndexRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/automod': {
      id: '/dashboard/servers/$guildId/automod'
      path: '/automod'
      fullPath: '/dashboard/servers/$guildId/automod'
      preLoaderRoute: typeof DashboardServersGuildIdAutomodRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/autoreact': {
      id: '/dashboard/servers/$guildId/autoreact'
      path: '/autoreact'
      fullPath: '/dashboard/servers/$guildId/autoreact'
      preLoaderRoute: typeof DashboardServersGuildIdAutoreactRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/autorole': {
      id: '/dashboard/servers/$guildId/autorole'
      path: '/autorole'
      fullPath: '/dashboard/servers/$guildId/autorole'
      preLoaderRoute: typeof DashboardServersGuildIdAutoroleRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/customroles': {
      id: '/dashboard/servers/$guildId/customroles'
      path: '/customroles'
      fullPath: '/dashboard/servers/$guildId/customroles'
      preLoaderRoute: typeof DashboardServersGuildIdCustomrolesRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/invcrole': {
      id: '/dashboard/servers/$guildId/invcrole'
      path: '/invcrole'
      fullPath: '/dashboard/servers/$guildId/invcrole'
      preLoaderRoute: typeof DashboardServersGuildIdInvcroleRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/invites': {
      id: '/dashboard/servers/$guildId/invites'
      path: '/invites'
      fullPath: '/dashboard/servers/$guildId/invites'
      preLoaderRoute: typeof DashboardServersGuildIdInvitesRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/j2c': {
      id: '/dashboard/servers/$guildId/j2c'
      path: '/j2c'
      fullPath: '/dashboard/servers/$guildId/j2c'
      preLoaderRoute: typeof DashboardServersGuildIdJ2cRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/joindm': {
      id: '/dashboard/servers/$guildId/joindm'
      path: '/joindm'
      fullPath: '/dashboard/servers/$guildId/joindm'
      preLoaderRoute: typeof DashboardServersGuildIdJoindmRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/leveling': {
      id: '/dashboard/servers/$guildId/leveling'
      path: '/leveling'
      fullPath: '/dashboard/servers/$guildId/leveling'
      preLoaderRoute: typeof DashboardServersGuildIdLevelingRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/logging': {
      id: '/dashboard/servers/$guildId/logging'
      path: '/logging'
      fullPath: '/dashboard/servers/$guildId/logging'
      preLoaderRoute: typeof DashboardServersGuildIdLoggingRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/protection': {
      id: '/dashboard/servers/$guildId/protection'
      path: '/protection'
      fullPath: '/dashboard/servers/$guildId/protection'
      preLoaderRoute: typeof DashboardServersGuildIdProtectionRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/reactionroles': {
      id: '/dashboard/servers/$guildId/reactionroles'
      path: '/reactionroles'
      fullPath: '/dashboard/servers/$guildId/reactionroles'
      preLoaderRoute: typeof DashboardServersGuildIdReactionrolesRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/tickets': {
      id: '/dashboard/servers/$guildId/tickets'
      path: '/tickets'
      fullPath: '/dashboard/servers/$guildId/tickets'
      preLoaderRoute: typeof DashboardServersGuildIdTicketsRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/tracking': {
      id: '/dashboard/servers/$guildId/tracking'
      path: '/tracking'
      fullPath: '/dashboard/servers/$guildId/tracking'
      preLoaderRoute: typeof DashboardServersGuildIdTrackingRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/vanityroles': {
      id: '/dashboard/servers/$guildId/vanityroles'
      path: '/vanityroles'
      fullPath: '/dashboard/servers/$guildId/vanityroles'
      preLoaderRoute: typeof DashboardServersGuildIdVanityrolesRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/verification': {
      id: '/dashboard/servers/$guildId/verification'
      path: '/verification'
      fullPath: '/dashboard/servers/$guildId/verification'
      preLoaderRoute: typeof DashboardServersGuildIdVerificationRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/dashboard/servers/$guildId/welcome': {
      id: '/dashboard/servers/$guildId/welcome'
      path: '/welcome'
      fullPath: '/dashboard/servers/$guildId/welcome'
      preLoaderRoute: typeof DashboardServersGuildIdWelcomeRouteImport
      parentRoute: typeof DashboardServersGuildIdRoute
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/login': {
      id: '/api/public/auth/discord/login'
      path: '/api/public/auth/discord/login'
      fullPath: '/api/public/auth/discord/login'
      preLoaderRoute: typeof ApiPublicAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminServersRouteChildren {
  AdminServersGuildIdRoute: typeof AdminServersGuildIdRoute
}

const AdminServersRouteChildren: AdminServersRouteChildren = {
  AdminServersGuildIdRoute: AdminServersGuildIdRoute,
}

const AdminServersRouteWithChildren = AdminServersRoute._addFileChildren(
  AdminServersRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminBotRoute: typeof AdminBotRoute
  AdminDatabaseRoute: typeof AdminDatabaseRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminServersRoute: typeof AdminServersRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApiRoute: AdminApiRoute,
  AdminBotRoute: AdminBotRoute,
  AdminDatabaseRoute: AdminDatabaseRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminServersRoute: AdminServersRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardServersGuildIdRouteChildren {
  DashboardServersGuildIdAutomodRoute: typeof DashboardServersGuildIdAutomodRoute
  DashboardServersGuildIdAutoreactRoute: typeof DashboardServersGuildIdAutoreactRoute
  DashboardServersGuildIdAutoroleRoute: typeof DashboardServersGuildIdAutoroleRoute
  DashboardServersGuildIdCustomrolesRoute: typeof DashboardServersGuildIdCustomrolesRoute
  DashboardServersGuildIdInvcroleRoute: typeof DashboardServersGuildIdInvcroleRoute
  DashboardServersGuildIdInvitesRoute: typeof DashboardServersGuildIdInvitesRoute
  DashboardServersGuildIdJ2cRoute: typeof DashboardServersGuildIdJ2cRoute
  DashboardServersGuildIdJoindmRoute: typeof DashboardServersGuildIdJoindmRoute
  DashboardServersGuildIdLevelingRoute: typeof DashboardServersGuildIdLevelingRoute
  DashboardServersGuildIdLoggingRoute: typeof DashboardServersGuildIdLoggingRoute
  DashboardServersGuildIdProtectionRoute: typeof DashboardServersGuildIdProtectionRoute
  DashboardServersGuildIdReactionrolesRoute: typeof DashboardServersGuildIdReactionrolesRoute
  DashboardServersGuildIdTicketsRoute: typeof DashboardServersGuildIdTicketsRoute
  DashboardServersGuildIdTrackingRoute: typeof DashboardServersGuildIdTrackingRoute
  DashboardServersGuildIdVanityrolesRoute: typeof DashboardServersGuildIdVanityrolesRoute
  DashboardServersGuildIdVerificationRoute: typeof DashboardServersGuildIdVerificationRoute
  DashboardServersGuildIdWelcomeRoute: typeof DashboardServersGuildIdWelcomeRoute
  DashboardServersGuildIdIndexRoute: typeof DashboardServersGuildIdIndexRoute
}

const DashboardServersGuildIdRouteChildren: DashboardServersGuildIdRouteChildren =
  {
    DashboardServersGuildIdAutomodRoute: DashboardServersGuildIdAutomodRoute,
    DashboardServersGuildIdAutoreactRoute:
      DashboardServersGuildIdAutoreactRoute,
    DashboardServersGuildIdAutoroleRoute: DashboardServersGuildIdAutoroleRoute,
    DashboardServersGuildIdCustomrolesRoute:
      DashboardServersGuildIdCustomrolesRoute,
    DashboardServersGuildIdInvcroleRoute: DashboardServersGuildIdInvcroleRoute,
    DashboardServersGuildIdInvitesRoute: DashboardServersGuildIdInvitesRoute,
    DashboardServersGuildIdJ2cRoute: DashboardServersGuildIdJ2cRoute,
    DashboardServersGuildIdJoindmRoute: DashboardServersGuildIdJoindmRoute,
    DashboardServersGuildIdLevelingRoute: DashboardServersGuildIdLevelingRoute,
    DashboardServersGuildIdLoggingRoute: DashboardServersGuildIdLoggingRoute,
    DashboardServersGuildIdProtectionRoute:
      DashboardServersGuildIdProtectionRoute,
    DashboardServersGuildIdReactionrolesRoute:
      DashboardServersGuildIdReactionrolesRoute,
    DashboardServersGuildIdTicketsRoute: DashboardServersGuildIdTicketsRoute,
    DashboardServersGuildIdTrackingRoute: DashboardServersGuildIdTrackingRoute,
    DashboardServersGuildIdVanityrolesRoute:
      DashboardServersGuildIdVanityrolesRoute,
    DashboardServersGuildIdVerificationRoute:
      DashboardServersGuildIdVerificationRoute,
    DashboardServersGuildIdWelcomeRoute: DashboardServersGuildIdWelcomeRoute,
    DashboardServersGuildIdIndexRoute: DashboardServersGuildIdIndexRoute,
  }

const DashboardServersGuildIdRouteWithChildren =
  DashboardServersGuildIdRoute._addFileChildren(
    DashboardServersGuildIdRouteChildren,
  )

interface DashboardServersRouteChildren {
  DashboardServersGuildIdRoute: typeof DashboardServersGuildIdRouteWithChildren
  DashboardServersIndexRoute: typeof DashboardServersIndexRoute
}

const DashboardServersRouteChildren: DashboardServersRouteChildren = {
  DashboardServersGuildIdRoute: DashboardServersGuildIdRouteWithChildren,
  DashboardServersIndexRoute: DashboardServersIndexRoute,
}

const DashboardServersRouteWithChildren =
  DashboardServersRoute._addFileChildren(DashboardServersRouteChildren)

interface DashboardRouteChildren {
  DashboardCommandsRoute: typeof DashboardCommandsRoute
  DashboardServersRoute: typeof DashboardServersRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCommandsRoute: DashboardCommandsRoute,
  DashboardServersRoute: DashboardServersRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommandsRoute: CommandsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  InviteRoute: InviteRoute,
  StatusRoute: StatusRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicAuthLogoutRoute: ApiPublicAuthLogoutRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordLoginRoute: ApiPublicAuthDiscordLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
